services:

  projet_etudes_sdv_m1-api:
    build: .
    # Use docker compose run api <command> to execute CLI subcommands
    volumes:
      - ./:/app
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  dvwa:
    image: vulnerables/web-dvwa
    entrypoint:
      - /bin/sh
      - -c
      - a2enmod ssl && a2ensite default-ssl && exec /main.sh
    ports:
      - "8080:80"
      - "8443:443"