services:

  projet_etudes_sdv_m1-api:
    build: .
    # Use docker compose run api <command> to execute CLI subcommands
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"